import '../models.dart';

const categoryDictionnaire = WordCategory(
  id: 'dictionnaire',
  name: 'Dictionnaire',
  icon: '📖',
  words: [

      // ÉMOTIONS POSITIVES - Facile
      WordWithDifficulty('Joie', difficulty: 1),
      WordWithDifficulty('Bonheur', difficulty: 1),
      WordWithDifficulty('Amour', difficulty: 1),
      WordWithDifficulty('Surprise', difficulty: 1),
      WordWithDifficulty('Plaisir', difficulty: 1),
      WordWithDifficulty('Calme', difficulty: 1),
      WordWithDifficulty('Confiance', difficulty: 1),
      WordWithDifficulty('Espoir', difficulty: 1),

      // ÉMOTIONS POSITIVES - Moyen
      WordWithDifficulty('Excitation', difficulty: 2),
      WordWithDifficulty('Enthousiasme', difficulty: 2),
      WordWithDifficulty('Tendresse', difficulty: 2),
      WordWithDifficulty('Fierté', difficulty: 2),
      WordWithDifficulty('Satisfaction', difficulty: 2),
      WordWithDifficulty('Soulagement', difficulty: 2),
      WordWithDifficulty('Admiration', difficulty: 2),
      WordWithDifficulty('Reconnaissance', difficulty: 2),
      WordWithDifficulty('Compassion', difficulty: 2),
      WordWithDifficulty('Sympathie', difficulty: 2),

      // ÉMOTIONS POSITIVES - Difficile
      WordWithDifficulty('Euphorie', difficulty: 3),
      WordWithDifficulty('Plénitude', difficulty: 3),
      WordWithDifficulty('Émerveillement', difficulty: 3),
      WordWithDifficulty('Gratitude', difficulty: 3),
      WordWithDifficulty('Sérénité', difficulty: 3),
      WordWithDifficulty('Béatitude', difficulty: 3),
      WordWithDifficulty('Exaltation', difficulty: 3),
      WordWithDifficulty('Ravissement', difficulty: 3),

      // ÉMOTIONS NÉGATIVES - Facile
      WordWithDifficulty('Tristesse', difficulty: 1),
      WordWithDifficulty('Colère', difficulty: 1),
      WordWithDifficulty('Peur', difficulty: 1),
      WordWithDifficulty('Douleur', difficulty: 1),
      WordWithDifficulty('Inquiétude', difficulty: 1),
      WordWithDifficulty('Regret', difficulty: 1),

      // ÉMOTIONS NÉGATIVES - Moyen
      WordWithDifficulty('Mélancolie', difficulty: 2),
      WordWithDifficulty('Angoisse', difficulty: 2),
      WordWithDifficulty('Jalousie', difficulty: 2),
      WordWithDifficulty('Honte', difficulty: 2),
      WordWithDifficulty('Ennui', difficulty: 2),
      WordWithDifficulty('Stress', difficulty: 2),
      WordWithDifficulty('Nostalgie', difficulty: 2),
      WordWithDifficulty('Déception', difficulty: 2),
      WordWithDifficulty('Impatience', difficulty: 2),
      WordWithDifficulty('Embarras', difficulty: 2),
      WordWithDifficulty('Solitude', difficulty: 2),

      // ÉMOTIONS NÉGATIVES - Difficile
      WordWithDifficulty('Chagrin', difficulty: 3),
      WordWithDifficulty('Désespoir', difficulty: 3),
      WordWithDifficulty('Fureur', difficulty: 3),
      WordWithDifficulty('Terreur', difficulty: 3),
      WordWithDifficulty('Panique', difficulty: 3),
      WordWithDifficulty('Dégoût', difficulty: 3),
      WordWithDifficulty('Mépris', difficulty: 3),
      WordWithDifficulty('Culpabilité', difficulty: 3),
      WordWithDifficulty('Humiliation', difficulty: 3),
      WordWithDifficulty('Frustration', difficulty: 3),
      WordWithDifficulty('Perplexité', difficulty: 3),
      WordWithDifficulty('Rancœur', difficulty: 3),
      WordWithDifficulty('Amertume', difficulty: 3),
      WordWithDifficulty('Consternation', difficulty: 3),

      // ADJECTIFS DESCRIPTIFS - Facile
      WordWithDifficulty('Grand', difficulty: 1),
      WordWithDifficulty('Petit', difficulty: 1),
      WordWithDifficulty('Beau', difficulty: 1),
      WordWithDifficulty('Joli', difficulty: 1),
      WordWithDifficulty('Gentil', difficulty: 1),
      WordWithDifficulty('Méchant', difficulty: 1),
      WordWithDifficulty('Heureux', difficulty: 1),
      WordWithDifficulty('Triste', difficulty: 1),
      WordWithDifficulty('Chaud', difficulty: 1),
      WordWithDifficulty('Froid', difficulty: 1),
      WordWithDifficulty('Facile', difficulty: 1),
      WordWithDifficulty('Difficile', difficulty: 1),
      WordWithDifficulty('Jeune', difficulty: 1),
      WordWithDifficulty('Vieux', difficulty: 1),
      WordWithDifficulty('Propre', difficulty: 1),
      WordWithDifficulty('Sale', difficulty: 1),

      // ADJECTIFS DESCRIPTIFS - Moyen
      WordWithDifficulty('Magnifique', difficulty: 2),
      WordWithDifficulty('Splendide', difficulty: 2),
      WordWithDifficulty('Courageux', difficulty: 2),
      WordWithDifficulty('Timide', difficulty: 2),
      WordWithDifficulty('Généreux', difficulty: 2),
      WordWithDifficulty('Intelligent', difficulty: 2),
      WordWithDifficulty('Stupide', difficulty: 2),
      WordWithDifficulty('Rapide', difficulty: 2),
      WordWithDifficulty('Lent', difficulty: 2),
      WordWithDifficulty('Fort', difficulty: 2),
      WordWithDifficulty('Faible', difficulty: 2),
      WordWithDifficulty('Amusant', difficulty: 2),
      WordWithDifficulty('Ennuyeux', difficulty: 2),
      WordWithDifficulty('Curieux', difficulty: 2),
      WordWithDifficulty('Patient', difficulty: 2),
      WordWithDifficulty('Honnête', difficulty: 2),
      WordWithDifficulty('Poli', difficulty: 2),
      WordWithDifficulty('Gentil', difficulty: 2),

      // ADJECTIFS COMPLEXES - Difficile
      WordWithDifficulty('Magnanime', difficulty: 3),
      WordWithDifficulty('Perspicace', difficulty: 3),
      WordWithDifficulty('Éloquent', difficulty: 3),
      WordWithDifficulty('Époustouflant', difficulty: 3),
      WordWithDifficulty('Majestueux', difficulty: 3),
      WordWithDifficulty('Téméraire', difficulty: 3),
      WordWithDifficulty('Intrépide', difficulty: 3),
      WordWithDifficulty('Pugnace', difficulty: 3),
      WordWithDifficulty('Circonspect', difficulty: 3),
      WordWithDifficulty('Méticuleux', difficulty: 3),
      WordWithDifficulty('Impétueux', difficulty: 3),
      WordWithDifficulty('Belliqueux', difficulty: 3),
      WordWithDifficulty('Versatile', difficulty: 3),
      WordWithDifficulty('Imperturbable', difficulty: 3),

      // VERBES DU QUOTIDIEN - Facile
      WordWithDifficulty('Marcher', difficulty: 1),
      WordWithDifficulty('Courir', difficulty: 1),
      WordWithDifficulty('Sauter', difficulty: 1),
      WordWithDifficulty('Manger', difficulty: 1),
      WordWithDifficulty('Boire', difficulty: 1),
      WordWithDifficulty('Dormir', difficulty: 1),
      WordWithDifficulty('Parler', difficulty: 1),
      WordWithDifficulty('Écouter', difficulty: 1),
      WordWithDifficulty('Regarder', difficulty: 1),
      WordWithDifficulty('Jouer', difficulty: 1),
      WordWithDifficulty('Rire', difficulty: 1),
      WordWithDifficulty('Pleurer', difficulty: 1),
      WordWithDifficulty('Penser', difficulty: 1),
      WordWithDifficulty('Aimer', difficulty: 1),

      // VERBES CRÉATIFS - Moyen
      WordWithDifficulty('Danser', difficulty: 2),
      WordWithDifficulty('Chanter', difficulty: 2),
      WordWithDifficulty('Dessiner', difficulty: 2),
      WordWithDifficulty('Écrire', difficulty: 2),
      WordWithDifficulty('Lire', difficulty: 2),
      WordWithDifficulty('Cuisiner', difficulty: 2),
      WordWithDifficulty('Conduire', difficulty: 2),
      WordWithDifficulty('Nager', difficulty: 2),
      WordWithDifficulty('Grimper', difficulty: 2),
      WordWithDifficulty('Construire', difficulty: 2),
      WordWithDifficulty('Peindre', difficulty: 2),
      WordWithDifficulty('Sculpter', difficulty: 2),
      WordWithDifficulty('Composer', difficulty: 2),
      WordWithDifficulty('Créer', difficulty: 2),

      // VERBES COMPLEXES - Difficile
      WordWithDifficulty('Ramper', difficulty: 3),
      WordWithDifficulty('Jongler', difficulty: 3),
      WordWithDifficulty('Escalader', difficulty: 3),
      WordWithDifficulty('Méditer', difficulty: 3),
      WordWithDifficulty('Scruter', difficulty: 3),
      WordWithDifficulty('Persévérer', difficulty: 3),
      WordWithDifficulty('Contempler', difficulty: 3),
      WordWithDifficulty('Sillonner', difficulty: 3),
      WordWithDifficulty('Vagabonder', difficulty: 3),
      WordWithDifficulty('Déambuler', difficulty: 3),
      WordWithDifficulty('Procrastiner', difficulty: 3),
      WordWithDifficulty('Divaguer', difficulty: 3),

      // ACTIONS PHYSIQUES - Facile
      WordWithDifficulty('Lever', difficulty: 1),
      WordWithDifficulty('Baisser', difficulty: 1),
      WordWithDifficulty('Tourner', difficulty: 1),
      WordWithDifficulty('Pousser', difficulty: 1),
      WordWithDifficulty('Tirer', difficulty: 1),
      WordWithDifficulty('Lancer', difficulty: 1),
      WordWithDifficulty('Attraper', difficulty: 1),
      WordWithDifficulty('Tomber', difficulty: 1),

      // ACTIONS PHYSIQUES - Moyen
      WordWithDifficulty('Soulever', difficulty: 2),
      WordWithDifficulty('Porter', difficulty: 2),
      WordWithDifficulty('Jeter', difficulty: 2),
      WordWithDifficulty('Frapper', difficulty: 2),
      WordWithDifficulty('Caresser', difficulty: 2),
      WordWithDifficulty('Applaudir', difficulty: 2),
      WordWithDifficulty('Siffler', difficulty: 2),
      WordWithDifficulty('Crier', difficulty: 2),

      // ACTIONS MENTALES - Moyen
      WordWithDifficulty('Réfléchir', difficulty: 2),
      WordWithDifficulty('Imaginer', difficulty: 2),
      WordWithDifficulty('Rêver', difficulty: 2),
      WordWithDifficulty('Comprendre', difficulty: 2),
      WordWithDifficulty('Apprendre', difficulty: 2),
      WordWithDifficulty('Mémoriser', difficulty: 2),
      WordWithDifficulty('Oublier', difficulty: 2),
      WordWithDifficulty('Décider', difficulty: 2),

      // ACTIONS MENTALES - Difficile
      WordWithDifficulty('Analyser', difficulty: 3),
      WordWithDifficulty('Synthétiser', difficulty: 3),
      WordWithDifficulty('Conceptualiser', difficulty: 3),
      WordWithDifficulty('Philosopher', difficulty: 3),
      WordWithDifficulty('Ratiociner', difficulty: 3),

      // ADVERBES DE MANIÈRE - Facile
      WordWithDifficulty('Bien', difficulty: 1),
      WordWithDifficulty('Mal', difficulty: 1),
      WordWithDifficulty('Vite', difficulty: 1),
      WordWithDifficulty('Lentement', difficulty: 1),

      // ADVERBES DE MANIÈRE - Moyen
      WordWithDifficulty('Rapidement', difficulty: 2),
      WordWithDifficulty('Doucement', difficulty: 2),
      WordWithDifficulty('Fortement', difficulty: 2),
      WordWithDifficulty('Souvent', difficulty: 2),
      WordWithDifficulty('Parfois', difficulty: 2),
      WordWithDifficulty('Jamais', difficulty: 2),
      WordWithDifficulty('Toujours', difficulty: 2),
      WordWithDifficulty('Ensemble', difficulty: 2),
      WordWithDifficulty('Seul', difficulty: 2),
      WordWithDifficulty('Énormément', difficulty: 2),

      // ADVERBES COMPLEXES - Difficile
      WordWithDifficulty('Promptement', difficulty: 3),
      WordWithDifficulty('Délicatement', difficulty: 3),
      WordWithDifficulty('Méticuleusement', difficulty: 3),
      WordWithDifficulty('Frénétiquement', difficulty: 3),
      WordWithDifficulty('Inlassablement', difficulty: 3),
      WordWithDifficulty('Inexorablement', difficulty: 3),
      WordWithDifficulty('Obstinément', difficulty: 3),
      WordWithDifficulty('Résolument', difficulty: 3),
      WordWithDifficulty('Vaillamment', difficulty: 3),
      WordWithDifficulty('Ardemment', difficulty: 3),
    
  ],
);
