import '../models.dart';

const categoryMarques = WordCategory(
  id: 'marques',
  name: 'Marques',
  icon: '🏷️',
  words: [

      // MARQUES DE VÊTEMENTS - Facile
      WordWithDifficulty('Nike', difficulty: 1),
      WordWithDifficulty('Adidas', difficulty: 1),
      WordWithDifficulty('Zara', difficulty: 1),
      WordWithDifficulty('H&M', difficulty: 1),
      WordWithDifficulty('Lacoste', difficulty: 1),
      WordWithDifficulty('Puma', difficulty: 1),
      WordWithDifficulty('Converse', difficulty: 1),
      WordWithDifficulty('Vans', difficulty: 1),

      // MARQUES DE VÊTEMENTS - Moyen
      WordWithDifficulty('Ralph Lauren', difficulty: 2),
      WordWithDifficulty('Tommy Hilfiger', difficulty: 2),
      WordWithDifficulty('Calvin Klein', difficulty: 2),
      WordWithDifficulty('Levi\'s', difficulty: 2),
      WordWithDifficulty('Diesel', difficulty: 2),
      WordWithDifficulty('Gap', difficulty: 2),
      WordWithDifficulty('Uniqlo', difficulty: 2),
      WordWithDifficulty('Mango', difficulty: 2),

      // MARQUES DE LUXE - Difficile
      WordWithDifficulty('Gucci', difficulty: 3),
      WordWithDifficulty('Prada', difficulty: 3),
      WordWithDifficulty('Chanel', difficulty: 3),
      WordWithDifficulty('Louis Vuitton', difficulty: 3),
      WordWithDifficulty('Hermès', difficulty: 3),
      WordWithDifficulty('Dior', difficulty: 3),
      WordWithDifficulty('Versace', difficulty: 3),
      WordWithDifficulty('Armani', difficulty: 3),
      WordWithDifficulty('Burberry', difficulty: 3),

      // MARQUES AUTOMOBILES - Facile
      WordWithDifficulty('Renault', difficulty: 1),
      WordWithDifficulty('Peugeot', difficulty: 1),
      WordWithDifficulty('Citroën', difficulty: 1),
      WordWithDifficulty('Volkswagen', difficulty: 1),
      WordWithDifficulty('Toyota', difficulty: 1),
      WordWithDifficulty('Ford', difficulty: 1),
      WordWithDifficulty('Mercedes', difficulty: 1),
      WordWithDifficulty('BMW', difficulty: 1),

      // MARQUES AUTOMOBILES - Moyen
      WordWithDifficulty('Audi', difficulty: 2),
      WordWithDifficulty('Nissan', difficulty: 2),
      WordWithDifficulty('Honda', difficulty: 2),
      WordWithDifficulty('Mazda', difficulty: 2),
      WordWithDifficulty('Hyundai', difficulty: 2),
      WordWithDifficulty('Kia', difficulty: 2),
      WordWithDifficulty('Fiat', difficulty: 2),
      WordWithDifficulty('Seat', difficulty: 2),
      WordWithDifficulty('Skoda', difficulty: 2),
      WordWithDifficulty('Opel', difficulty: 2),

      // MARQUES AUTOMOBILES LUXE - Difficile
      WordWithDifficulty('Ferrari', difficulty: 1),
      WordWithDifficulty('Lamborghini', difficulty: 3),
      WordWithDifficulty('Porsche', difficulty: 1),
      WordWithDifficulty('Maserati', difficulty: 3),
      WordWithDifficulty('Bugatti', difficulty: 3),
      WordWithDifficulty('Bentley', difficulty: 3),
      WordWithDifficulty('Rolls-Royce', difficulty: 3),
      WordWithDifficulty('Aston Martin', difficulty: 3),

      // MARQUES TECHNOLOGIE - Facile
      WordWithDifficulty('Apple', difficulty: 1),
      WordWithDifficulty('Samsung', difficulty: 1),
      WordWithDifficulty('Microsoft', difficulty: 1),
      WordWithDifficulty('Google', difficulty: 1),
      WordWithDifficulty('Sony', difficulty: 2),
      WordWithDifficulty('LG', difficulty: 2),
      WordWithDifficulty('HP', difficulty: 2),
      WordWithDifficulty('Dell', difficulty: 2),

      // MARQUES TECHNOLOGIE - Moyen
      WordWithDifficulty('Asus', difficulty: 2),
      WordWithDifficulty('Lenovo', difficulty: 2),
      WordWithDifficulty('Acer', difficulty: 3),
      WordWithDifficulty('Philips', difficulty: 2),
      WordWithDifficulty('Panasonic', difficulty: 3),
      WordWithDifficulty('Toshiba', difficulty: 3),
      WordWithDifficulty('Huawei', difficulty: 3),
      WordWithDifficulty('Xiaomi', difficulty: 3),

      // MARQUES ALIMENTATION - Facile
      WordWithDifficulty('Coca-Cola', difficulty: 1),
      WordWithDifficulty('Pepsi', difficulty: 1),
      WordWithDifficulty('Nutella', difficulty: 1),
      WordWithDifficulty('Kinder', difficulty: 1),
      WordWithDifficulty('Haribo', difficulty: 1),
      WordWithDifficulty('Nestlé', difficulty: 1),
      WordWithDifficulty('Danone', difficulty: 1),
      WordWithDifficulty('Lu', difficulty: 1),
      WordWithDifficulty('Fanta', difficulty: 1),
      WordWithDifficulty('Sprite', difficulty: 1),
      WordWithDifficulty('Orangina', difficulty: 1),
      WordWithDifficulty('Evian', difficulty: 1),
      WordWithDifficulty('Volvic', difficulty: 1),
      WordWithDifficulty('Perrier', difficulty: 1),
      WordWithDifficulty('Heinz', difficulty: 1),
      WordWithDifficulty('Président', difficulty: 1),
      WordWithDifficulty('Capri-Sun', difficulty: 2),
      WordWithDifficulty('Tropicana', difficulty: 1),
      WordWithDifficulty('Bonne Maman', difficulty: 1),
      WordWithDifficulty('Panzani', difficulty: 1),
      WordWithDifficulty('Barilla', difficulty: 1),
      WordWithDifficulty('Herta', difficulty: 1),
      WordWithDifficulty('Fleury Michon', difficulty: 1),
      WordWithDifficulty('Charal', difficulty: 1),
      WordWithDifficulty('Bonduelle', difficulty: 1),
      WordWithDifficulty('Yoplait', difficulty: 1),
      WordWithDifficulty('Activia', difficulty: 1),
      WordWithDifficulty('Kellogg\'s', difficulty: 1),
      WordWithDifficulty('Céréales Lion', difficulty: 1),

      // MARQUES ALIMENTATION - Moyen
      WordWithDifficulty('Mars', difficulty: 2),
      WordWithDifficulty('Snickers', difficulty: 2),
      WordWithDifficulty('Milka', difficulty: 2),
      WordWithDifficulty('Ferrero', difficulty: 2),
      WordWithDifficulty('Lindt', difficulty: 2),
      WordWithDifficulty('Pringles', difficulty: 2),
      WordWithDifficulty('Lay\'s', difficulty: 2),
      WordWithDifficulty('Oreo', difficulty: 2),
      WordWithDifficulty('KitKat', difficulty: 2),
      WordWithDifficulty('Ben & Jerry\'s', difficulty: 2),
      WordWithDifficulty('Twix', difficulty: 2),
      WordWithDifficulty('Bounty', difficulty: 2),
      WordWithDifficulty('M&M\'s', difficulty: 2),
      WordWithDifficulty('Skittles', difficulty: 2),
      WordWithDifficulty('Tic Tac', difficulty: 2),
      WordWithDifficulty('Mentos', difficulty: 2),
      WordWithDifficulty('Chupa Chups', difficulty: 2),
      WordWithDifficulty('Carambar', difficulty: 2),
      WordWithDifficulty('Malabar', difficulty: 2),
      WordWithDifficulty('Tagada', difficulty: 2),
      WordWithDifficulty('Dragibus', difficulty: 2),
      WordWithDifficulty('Red Bull', difficulty: 2),
      WordWithDifficulty('Monster Energy', difficulty: 2),
      WordWithDifficulty('Oasis', difficulty: 2),
      WordWithDifficulty('Schweppes', difficulty: 2),
      WordWithDifficulty('Lipton', difficulty: 2),
      WordWithDifficulty('Cristaline', difficulty: 2),
      WordWithDifficulty('Badoit', difficulty: 2),
      WordWithDifficulty('San Pellegrino', difficulty: 2),
      WordWithDifficulty('Contrex', difficulty: 2),
      WordWithDifficulty('Vittel', difficulty: 2),
      WordWithDifficulty('Amora', difficulty: 2),
      WordWithDifficulty('Maille', difficulty: 2),
      WordWithDifficulty('Kikkoman', difficulty: 2),
      WordWithDifficulty('Tabasco', difficulty: 2),
      WordWithDifficulty('Philadelphia', difficulty: 2),
      WordWithDifficulty('Babybel', difficulty: 2),
      WordWithDifficulty('La Vache qui rit', difficulty: 2),
      WordWithDifficulty('Kiri', difficulty: 2),
      WordWithDifficulty('Boursin', difficulty: 2),
      WordWithDifficulty('Caprice des Dieux', difficulty: 2),
      WordWithDifficulty('Saint Môret', difficulty: 2),
      WordWithDifficulty('Häagen-Dazs', difficulty: 2),
      WordWithDifficulty('Magnum', difficulty: 2),
      WordWithDifficulty('Carte d\'Or', difficulty: 2),
      WordWithDifficulty('Brossard', difficulty: 2),
      WordWithDifficulty('St Michel', difficulty: 2),
      WordWithDifficulty('Gerblé', difficulty: 2),
      WordWithDifficulty('Bjorg', difficulty: 3),
      WordWithDifficulty('Uncle Ben\'s', difficulty: 2),
      WordWithDifficulty('Ebly', difficulty: 3),
      WordWithDifficulty('Lustucru', difficulty: 2),
      WordWithDifficulty('Tipiak', difficulty: 2),
      WordWithDifficulty('Cassegrain', difficulty: 2),
      WordWithDifficulty('D\'aucy', difficulty: 2),
      WordWithDifficulty('Géant Vert', difficulty: 2),
      WordWithDifficulty('William Saurin', difficulty: 3),
      WordWithDifficulty('Côte d\'Or', difficulty: 2),
      WordWithDifficulty('Toblerone', difficulty: 2),
      WordWithDifficulty('Merci', difficulty: 2),
      WordWithDifficulty('Raffaello', difficulty: 2),
      WordWithDifficulty('Ferrero Rocher', difficulty: 2),
      WordWithDifficulty('Mon Chéri', difficulty: 2),
      WordWithDifficulty('Celebrations', difficulty: 2),

      // MARQUES ALIMENTATION - Difficile
      WordWithDifficulty('Poulain', difficulty: 3),
      WordWithDifficulty('Banania', difficulty: 3),
      WordWithDifficulty('Ricoré', difficulty: 3),
      WordWithDifficulty('Belvita', difficulty: 3),
      WordWithDifficulty('Grany', difficulty: 3),
      WordWithDifficulty('Pitch', difficulty: 3),
      WordWithDifficulty('Savane', difficulty: 3),
      WordWithDifficulty('Napolitain', difficulty: 3),
      WordWithDifficulty('Granola', difficulty: 3),
      WordWithDifficulty('Petit Écolier', difficulty: 3),
      WordWithDifficulty('Paille d\'Or', difficulty: 3),
      WordWithDifficulty('Petit Beurre', difficulty: 3),
      WordWithDifficulty('BN', difficulty: 2),
      WordWithDifficulty('Mikado', difficulty: 3),
      WordWithDifficulty('Pepito', difficulty: 3),
      WordWithDifficulty('Prince', difficulty: 2),
      WordWithDifficulty('Figolu', difficulty: 3),
      WordWithDifficulty('Finger', difficulty: 3),
      WordWithDifficulty('Pépito', difficulty: 3),
      WordWithDifficulty('Curly', difficulty: 3),
      WordWithDifficulty('Benenuts', difficulty: 3),
      WordWithDifficulty('Vico', difficulty: 3),
      WordWithDifficulty('Apéricube', difficulty: 3),
      WordWithDifficulty('Tuc', difficulty: 3),
      WordWithDifficulty('Cracotte', difficulty: 3),
      WordWithDifficulty('Krisprolls', difficulty: 3),

      // MARQUES FAST-FOOD - Facile
      WordWithDifficulty('McDonald\'s', difficulty: 1),
      WordWithDifficulty('Burger King', difficulty: 1),
      WordWithDifficulty('KFC', difficulty: 1),
      WordWithDifficulty('Quick', difficulty: 1),
      WordWithDifficulty('Subway', difficulty: 1),
      WordWithDifficulty('Domino\'s', difficulty: 1),
      WordWithDifficulty('Pizza Hut', difficulty: 1),
      WordWithDifficulty('Paul', difficulty: 2),
      WordWithDifficulty('Brioche Dorée', difficulty: 2),

      // MARQUES FAST-FOOD - Moyen
      WordWithDifficulty('Five Guys', difficulty: 2),
      WordWithDifficulty('Chipotle', difficulty: 2),
      WordWithDifficulty('Starbucks', difficulty: 2),
      WordWithDifficulty('Dunkin\' Donuts', difficulty: 2),
      WordWithDifficulty('Buffalo Grill', difficulty: 2),
      WordWithDifficulty('Hippopotamus', difficulty: 2),
      WordWithDifficulty('Courtepaille', difficulty: 2),
      WordWithDifficulty('Flunch', difficulty: 2),
      WordWithDifficulty('Léon de Bruxelles', difficulty: 2),

      // MAGASINS - Facile
      WordWithDifficulty('Carrefour', difficulty: 1),
      WordWithDifficulty('Auchan', difficulty: 1),
      WordWithDifficulty('Leclerc', difficulty: 1),
      WordWithDifficulty('Lidl', difficulty: 1),
      WordWithDifficulty('Ikea', difficulty: 1),
      WordWithDifficulty('Fnac', difficulty: 1),
      WordWithDifficulty('Darty', difficulty: 1),
      WordWithDifficulty('Décathlon', difficulty: 1),

      // MAGASINS - Moyen
      WordWithDifficulty('Leroy Merlin', difficulty: 2),
      WordWithDifficulty('Castorama', difficulty: 2),
      WordWithDifficulty('Boulanger', difficulty: 2),
      WordWithDifficulty('Conforama', difficulty: 2),
      WordWithDifficulty('But', difficulty: 2),
      WordWithDifficulty('Monoprix', difficulty: 2),
      WordWithDifficulty('Franprix', difficulty: 2),
      WordWithDifficulty('Intermarché', difficulty: 2),

      // MARQUES BRICOLAGE - Moyen
      WordWithDifficulty('Bosch', difficulty: 2),
      WordWithDifficulty('Karcher', difficulty: 2),

      // MARQUES COSMÉTIQUES - Moyen
      WordWithDifficulty('L\'Oréal', difficulty: 2),
      WordWithDifficulty('Maybelline', difficulty: 2),
      WordWithDifficulty('Nivea', difficulty: 2),
      WordWithDifficulty('Garnier', difficulty: 2),
      WordWithDifficulty('Dove', difficulty: 2),
      WordWithDifficulty('Lancôme', difficulty: 2),

      // MARQUES SPORT - Moyen
      WordWithDifficulty('Reebok', difficulty: 2),
      WordWithDifficulty('New Balance', difficulty: 2),
      WordWithDifficulty('Asics', difficulty: 2),
      WordWithDifficulty('Under Armour', difficulty: 3),
      WordWithDifficulty('The North Face', difficulty: 2),
      WordWithDifficulty('Columbia', difficulty: 2),
      WordWithDifficulty('Quiksilver', difficulty: 2),

      // MARQUES JOUETS - Moyen
      WordWithDifficulty('Lego', difficulty: 2),
      WordWithDifficulty('Playmobil', difficulty: 2),
      WordWithDifficulty('Barbie', difficulty: 2),
      WordWithDifficulty('Hot Wheels', difficulty: 2),
      WordWithDifficulty('Nerf', difficulty: 2),
    
  ],
);
