import '../models.dart';

const categoryMetroParisien = WordCategory(
  id: 'metro_parisien',
  name: 'Métro Parisien',
  icon: '🚇',
  words: [

      // STATIONS CÉLÈBRES - Facile
      WordWithDifficulty('Châtelet', difficulty: 1),
      WordWithDifficulty('Gare du Nord', difficulty: 1),
      WordWithDifficulty('Gare de Lyon', difficulty: 1),
      WordWithDifficulty('République', difficulty: 1),
      WordWithDifficulty('Bastille', difficulty: 1),
      WordWithDifficulty('Nation', difficulty: 1),
      WordWithDifficulty('Opéra', difficulty: 1),
      WordWithDifficulty('Concorde', difficulty: 1),
      WordWithDifficulty('Invalides', difficulty: 1),
      WordWithDifficulty('Étoile', difficulty: 1),
      WordWithDifficulty('Trocadéro', difficulty: 1),
      WordWithDifficulty('La Défense', difficulty: 1),

      // STATIONS CENTRALES - Moyen
      WordWithDifficulty('Saint-Lazare', difficulty: 2),
      WordWithDifficulty('Montparnasse', difficulty: 2),
      WordWithDifficulty('Denfert-Rochereau', difficulty: 2),
      WordWithDifficulty('Hôtel de Ville', difficulty: 2),
      WordWithDifficulty('Réaumur-Sébastopol', difficulty: 2),
      WordWithDifficulty('Strasbourg-Saint-Denis', difficulty: 2),
      WordWithDifficulty('Barbès-Rochechouart', difficulty: 2),
      WordWithDifficulty('Belleville', difficulty: 2),
      WordWithDifficulty('Pigalle', difficulty: 2),
      WordWithDifficulty('Champs-Élysées', difficulty: 2),
      WordWithDifficulty('Franklin D. Roosevelt', difficulty: 2),
      WordWithDifficulty('Saint-Michel', difficulty: 2),
      WordWithDifficulty('Odéon', difficulty: 2),
      WordWithDifficulty('Luxembourg', difficulty: 2),
      WordWithDifficulty('Palais Royal', difficulty: 2),
      WordWithDifficulty('Louvre-Rivoli', difficulty: 2),
      WordWithDifficulty('Pyramides', difficulty: 2),
      WordWithDifficulty('Madeleine', difficulty: 2),

      // STATIONS LIGNE 1 - Moyen
      WordWithDifficulty('Esplanade de La Défense', difficulty: 2),
      WordWithDifficulty('Pont de Neuilly', difficulty: 2),
      WordWithDifficulty('Porte Maillot', difficulty: 2),
      WordWithDifficulty('Argentine', difficulty: 2),
      WordWithDifficulty('George V', difficulty: 2),
      WordWithDifficulty('Champs-Élysées-Clemenceau', difficulty: 2),
      WordWithDifficulty('Tuileries', difficulty: 2),
      WordWithDifficulty('Châtelet-Les Halles', difficulty: 2),
      WordWithDifficulty('Saint-Paul', difficulty: 2),
      WordWithDifficulty('Château de Vincennes', difficulty: 2),

      // STATIONS PÉRIPHÉRIQUES - Moyen
      WordWithDifficulty('Porte de Clignancourt', difficulty: 2),
      WordWithDifficulty('Porte de Versailles', difficulty: 2),
      WordWithDifficulty('Porte d\'Orléans', difficulty: 2),
      WordWithDifficulty('Porte de Bagnolet', difficulty: 2),
      WordWithDifficulty('Porte de Vincennes', difficulty: 2),
      WordWithDifficulty('Porte de Pantin', difficulty: 2),
      WordWithDifficulty('Porte de Champerret', difficulty: 2),
      WordWithDifficulty('Porte Dauphine', difficulty: 2),

      // STATIONS PITTORESQUES - Difficile
      WordWithDifficulty('Abbesses', difficulty: 3),
      WordWithDifficulty('Anvers', difficulty: 3),
      WordWithDifficulty('Blanche', difficulty: 3),
      WordWithDifficulty('Cluny-La Sorbonne', difficulty: 3),
      WordWithDifficulty('Maubert-Mutualité', difficulty: 3),
      WordWithDifficulty('Cardinal Lemoine', difficulty: 3),
      WordWithDifficulty('Jussieu', difficulty: 3),
      WordWithDifficulty('Sully-Morland', difficulty: 3),
      WordWithDifficulty('Quai de la Rapée', difficulty: 3),
      WordWithDifficulty('Bir-Hakeim', difficulty: 3),
      WordWithDifficulty('Passy', difficulty: 3),
      WordWithDifficulty('La Muette', difficulty: 3),
      WordWithDifficulty('Jasmin', difficulty: 3),
      WordWithDifficulty('Ranelagh', difficulty: 3),
      WordWithDifficulty('Michel-Ange Auteuil', difficulty: 3),
      WordWithDifficulty('Boulogne-Jean Jaurès', difficulty: 3),

      // STATIONS BANLIEUE - Difficile
      WordWithDifficulty('Créteil-Préfecture', difficulty: 3),
      WordWithDifficulty('Mairie de Montreuil', difficulty: 3),
      WordWithDifficulty('Bobigny-Pablo Picasso', difficulty: 3),
      WordWithDifficulty('Villejuif-Louis Aragon', difficulty: 3),
      WordWithDifficulty('Mairie d\'Issy', difficulty: 3),
      WordWithDifficulty('Mairie de Saint-Ouen', difficulty: 3),
      WordWithDifficulty('Gallieni', difficulty: 3),
      WordWithDifficulty('Boulogne-Pont de Saint-Cloud', difficulty: 3),

      // STATIONS CULTURELLES - Difficile
      WordWithDifficulty('Arts et Métiers', difficulty: 3),
      WordWithDifficulty('Parmentier', difficulty: 3),
      WordWithDifficulty('Voltaire', difficulty: 3),
      WordWithDifficulty('Charonne', difficulty: 3),
      WordWithDifficulty('Alexandre Dumas', difficulty: 3),
      WordWithDifficulty('Avron', difficulty: 3),
      WordWithDifficulty('Buzenval', difficulty: 3),
      WordWithDifficulty('Maraîchers', difficulty: 3),
      WordWithDifficulty('Faidherbe-Chaligny', difficulty: 3),
      WordWithDifficulty('Ledru-Rollin', difficulty: 3),
      WordWithDifficulty('Bréguet-Sabin', difficulty: 3),
      WordWithDifficulty('Chemin Vert', difficulty: 3),
      WordWithDifficulty('Saint-Sébastien-Froissart', difficulty: 3),
      WordWithDifficulty('Filles du Calvaire', difficulty: 3),
      WordWithDifficulty('Oberkampf', difficulty: 3),
      WordWithDifficulty('Temple', difficulty: 3),
      WordWithDifficulty('Rambuteau', difficulty: 3),
      WordWithDifficulty('Étienne Marcel', difficulty: 3),
      WordWithDifficulty('Sentier', difficulty: 3),
      WordWithDifficulty('Bonne Nouvelle', difficulty: 3),
      WordWithDifficulty('Poissonnière', difficulty: 3),
      WordWithDifficulty('Cadet', difficulty: 3),
      WordWithDifficulty('Le Peletier', difficulty: 3),
      WordWithDifficulty('Chaussée d\'Antin', difficulty: 3),
      WordWithDifficulty('Havre-Caumartin', difficulty: 3),
      WordWithDifficulty('Saint-Augustin', difficulty: 3),
      WordWithDifficulty('Miromesnil', difficulty: 3),
      WordWithDifficulty('Saint-Philippe du Roule', difficulty: 3),
      WordWithDifficulty('Alma-Marceau', difficulty: 3),
      WordWithDifficulty('Iéna', difficulty: 3),
      WordWithDifficulty('Boissière', difficulty: 3),
      WordWithDifficulty('Kléber', difficulty: 3),
      WordWithDifficulty('Victor Hugo', difficulty: 3),
    
  ],
);
